{% set name = "pyapacheatlas" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyapacheatlas-{{ version }}.tar.gz
  sha256: 8286bd99771c64d90131dd6be8f858369bcc980dde527ba07cc50eca773dced0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - openpyxl >=3.0
    - requests >=2.0

test:
  imports:
    - pyapacheatlas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wjohnson/pyapacheatlas
  summary: A package to simplify working with the Apache Atlas REST APIs for Atlas and Azure Purview.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
